[package]
name = "lightstatic"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "lightstatic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
